// <auto-generated />
namespace Senai.Chamados.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Cria_tabela_Chamados_04_07_20181 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cria_tabela_Chamados_04_07_20181));
        
        string IMigrationMetadata.Id
        {
            get { return "201807042230165_Cria_tabela_Chamados_04_07_20181"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
